<h1>Items:</h1>

<?php if($item): ?>
    <h3><?php echo $this->escapeHtml(ucwords($item->title)); ?></h3>

    <div style="width: 250px; float: left;">
        <?php if($item->photo_filename): ?>
            <img src="<?php echo $item->photo_filename; ?>" />
        <?php else: ?>
            No Image
        <?php endif; ?>
    </div>

    <div style="width: 400px;float:left;margin: 20px">
        <b>Contact Details</b>
        <br><?php $this->escapeHtml($item->contact_name) ?>
        <br><?php $this->escapeHtml($item->contact_email) ?>
        <br><?php $this->escapeHtml($item->contact_phone) ?>
        <br><b>Posting Details</b>
        <br><?php $this->escapeHtml($item->date_created) ?>
        <br>Price: <?php $this->escapeHtml($item->price) ?>
        <br>City: <?php $this->escapeHtml($item->city) ?>, <?php $this->escapeHtml($item->country) ?>
        <br>Description:
        <p><?php $this->escapeHtml($item->description) ?></p>
    </div>

<?php else: ?>
    No recent Post
<?php endif; ?>